/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package_main;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author nihar, ojaswini, mudit
 */
public class BookingPage extends javax.swing.JFrame {
    String number;
    private void mySQLConnection(int adult_num,int child_num,Date in_date, Date out_date,int rooms_num) throws SQLException{
        try {
            // Connect to the MySQL database using the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/sit"; 
            String user = "root";
            String password = "toor";
            Connection con = DriverManager.getConnection(url, user, password);
            String s = "UPDATE radission_java SET adult_num = ?, child_num = ?, in_date = ?, out_date = ?, rooms_num = ? WHERE phone = ?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setInt(1, adult_num);
            ps.setInt(2, child_num);
            ps.setDate(3, new java.sql.Date(in_date.getTime()));
            ps.setDate(4, new java.sql.Date(out_date.getTime()));
            ps.setInt(5, rooms_num);
            ps.setString(6, number);


            int result = ps.executeUpdate(); //returns 1 if successful
            if (result == 1)
                System.out.println("Successfully Entered Record");
            else
                System.out.println("Error in inserting Record!"); 
        } catch (ClassNotFoundException | SQLException ex) {
            // Handle any exceptions that may occur while connecting to the database
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    /*
     * Creates new form BookingPage
     */ 
    
    public BookingPage() {
        initComponents();
    }
    public BookingPage(String num) {
        initComponents();
        this.number = num;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(775, 360));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(143, 36, 495, 33);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Check in date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(431, 75, 110, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Number of adults:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(47, 75, 150, 21);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Number of children:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(31, 131, 160, 21);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("(Below 10 years of age)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(16, 159, 180, 21);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(567, 75, 168, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Check out date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(421, 131, 120, 21);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(567, 131, 168, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(214, 76, 72, 21);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(214, 132, 72, 21);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("FIND ROOMS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(319, 256, 150, 41);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Number of rooms:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(259, 207, 143, 21);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(426, 208, 72, 21);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\bg_new.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 760, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public static boolean isTwoMonthsAfter(Calendar date1, Calendar date2) {
        Calendar date2TwoMonthsAfter = (Calendar) date1.clone();
        date2TwoMonthsAfter.add(Calendar.MONTH, 2);
        return date2.equals(date2TwoMonthsAfter);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jDateChooser1.getDate() == null || jDateChooser2.getDate() == null){
           String message = "Check-in and check-out dates cannot be empty!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        Date checkIn = jDateChooser1.getDate();
        Date checkOut = jDateChooser2.getDate();
        
        Calendar cal1 = Calendar.getInstance();
        cal1.setTime(checkIn);

        Calendar cal2 = Calendar.getInstance();
        cal2.setTime(checkOut);
        
        Calendar calToday = Calendar.getInstance();
        Calendar calMaxDate = Calendar.getInstance();
        calMaxDate.add(Calendar.MONTH, 3);

        // Add 2 months to the check-in date
        cal1.add(Calendar.MONTH, 2);
        System.out.println(checkIn);
        System.out.println(checkOut);
        
        if (getAdults() + getChildren() > 4 && getRooms() == 1 ) {
            String message = "Sorry, you cannot select 1 room for more than 4 guests!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
        JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (checkIn.before(calToday.getTime())) {
            String message = "Check-in date cannot be before today!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
        JOptionPane.ERROR_MESSAGE);
            return;
        } else if (checkIn.after(calMaxDate.getTime())) {
            String message = "Check-in date cannot be more than 3 months from today!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
        JOptionPane.ERROR_MESSAGE);
            return;

        }else if (checkIn.after(checkOut)){
            String message = "Check-out cannot be before Check-in!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
        JOptionPane.ERROR_MESSAGE);
            return;
        }else if (!cal1.before(cal2)) {
            dispose();
            GetRoom userRoomChoice = new GetRoom(number, getRooms());
            userRoomChoice.setVisible(true);
        } else{
            String message = "Check-out cannot be more than 2 months after Check-in!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
        JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
                mySQLConnection(getAdults(),getChildren(),checkIn,checkOut,getRooms());
        } catch (SQLException ex) {
                // Handle any exceptions that may occur while connecting to the database
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(1);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    public int getAdults() {
        String Adults = (String) jComboBox1.getSelectedItem();
        int numOfAdults = Integer.parseInt(Adults);
        return numOfAdults;
    }
    public int getChildren() {
        String Children = (String) jComboBox2.getSelectedItem();
        int numOfChildren = Integer.parseInt(Children);
        return numOfChildren;
    }
    public Date getCheckIn() {
        Date checkIn = jDateChooser1.getDate();
        return checkIn;
    }
    public Date getCheckOut() {
        Date checkOut = jDateChooser2.getDate();
        return checkOut;
    }
    public int getRooms() {
        String room = (String)jComboBox3.getSelectedItem();
        int rooms = Integer.parseInt(room);
        return rooms;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BookingPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
