/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package_main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author nihar, ojaswini, mudit
 */
public class UserSummary extends javax.swing.JFrame {
    String phone;
    String name;
    Date in_date;
    Date out_date;
    int rooms_num;
    int delux_num;
    int suite_num;
    int standard_num;
    int villa_num;
    double bill;
    /**
     * Creates new form UserSummary
     */
    public UserSummary() {
    initComponents();
    }
    public UserSummary(String phone) {
        initComponents();
        this.phone = phone;
        try{
            mySQLConnection(phone);
        } catch (SQLException ex) {
            // Handle any exceptions that may occur while connecting to the database
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        setBill();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        jLabel7.setText("Date of Invoice:");

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(649, 669));
        setPreferredSize(new java.awt.Dimension(649, 669));
        getContentPane().setLayout(null);

        jLabel19.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel19.setText("The Radission World");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(70, 40, 360, 30);

        jLabel20.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel20.setText("Hotel ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 20, 90, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\hotel.png")); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(20, 20, 40, 40);

        jLabel18.setText("GSTIN: 22ABCDE1234F1ZH");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(450, 130, 160, 16);

        jLabel22.setText("PAN: ABCDE1234F");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(500, 110, 110, 16);

        jLabel26.setText("Survey No. 174/1,");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(510, 30, 100, 16);

        jLabel28.setText("Maharashtra, India");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(500, 90, 110, 16);

        jLabel29.setText("Pune-Bangalore Hwy");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(490, 50, 120, 16);

        jLabel30.setText("Baner, Pune - 411045,");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(480, 70, 130, 16);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\email.png")); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(20, 70, 20, 20);

        jLabel23.setText("hello@radissionworld.in");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(40, 70, 140, 16);

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\web.png")); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(190, 70, 20, 20);

        jLabel25.setText("radissionworld.in");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(210, 70, 100, 16);

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\phone-call.png")); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(320, 70, 20, 16);

        jLabel33.setText("020 8888 8888");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(350, 70, 80, 16);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("jTextField8");
        jTextField8.setBorder(null);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(530, 170, 80, 16);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("jTextField9");
        jTextField9.setBorder(null);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(530, 190, 80, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Date of Invoice:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 170, 100, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Period of Stay: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 190, 90, 16);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("jTextField10");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(500, 380, 90, 16);

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 150, 360, 5);

        jPanel3.setBackground(new java.awt.Color(56, 182, 255));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(370, 150, 240, 5);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(25);
        jTextArea3.setRows(5);
        jTextArea3.setAutoscrolls(false);
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);
        jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(210, 260, 60, 140);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea6.setColumns(25);
        jTextArea6.setRows(5);
        jTextArea6.setAutoscrolls(false);
        jTextArea6.setBorder(null);
        jScrollPane6.setViewportView(jTextArea6);
        jScrollPane6.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(290, 260, 60, 140);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Disclaimer:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 420, 80, 16);

        jTextArea5.setColumns(25);
        jTextArea5.setRows(5);
        jTextArea5.setText("The hotel bill includes GST taxes as per the \napplicable laws. Tax rates and charges are \nsubject to change. \nAny issues arising from this bill will be \nsubject to jurisdiction of  Pune courts only.");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setAutoscrolls(false);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(30, 440, 260, 110);

        jPanel4.setBackground(new java.awt.Color(51, 0, 153));
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Description");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 10, 70, 16);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Number ");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(180, 0, 50, 16);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("of Rooms");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(180, 10, 60, 16);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Number ");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(260, 0, 50, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("of Days");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(260, 10, 60, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price (in INR)");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(350, 10, 90, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total (in INR)");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(470, 10, 90, 16);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 220, 580, 30);

        jLabel37.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel37.setText("MUDIT GARG");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(490, 570, 110, 17);

        jLabel38.setText("Administrator");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel38);
        jLabel38.setBounds(520, 590, 100, 16);

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\sign.png")); // NOI18N
        jPanel1.add(jLabel40);
        jLabel40.setBounds(500, 540, 91, 32);

        jPanel6.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.add(jPanel6);
        jPanel6.setBounds(350, 610, 280, 20);

        jPanel7.setBackground(new java.awt.Color(82, 113, 255));
        jPanel1.add(jPanel7);
        jPanel7.setBounds(160, 610, 190, 10);

        jPanel5.setBackground(new java.awt.Color(56, 182, 255));
        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 620, 350, 10);
        jPanel5.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVOICE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, 100, 237, 29);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 170, 50, 16);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("jTextField4");
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(90, 170, 130, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Phone No. :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 190, 70, 16);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("jTextField4");
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(90, 190, 130, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Check In Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 170, 90, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Check Out Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 190, 100, 16);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("jTextField6");
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(330, 170, 90, 16);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("jTextField7");
        jTextField7.setBorder(null);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(330, 190, 90, 16);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(25);
        jTextArea2.setRows(5);
        jTextArea2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea2);
        jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 260, 150, 140);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea4.setColumns(25);
        jTextArea4.setRows(5);
        jTextArea4.setAutoscrolls(false);
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);
        jScrollPane4.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(370, 260, 90, 140);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(25);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(500, 260, 110, 120);

        jTextField2.setEditable(false);
        jTextField2.setText("jTextField1");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(500, 420, 90, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("GST:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(470, 420, 43, 16);

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(500, 450, 90, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Hotel Taxes:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(420, 450, 80, 16);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(500, 490, 90, 26);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Net Payble:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(410, 490, 90, 20);

        jLabel27.setText("The Radisson World");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(500, 10, 110, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 630);

        getAccessibleContext().setAccessibleParent(jScrollPane6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserSummary().setVisible(true);
//            }
//        });
//    }

    private void mySQLConnection(String phone) throws SQLException{
        try {
            // Connect to the MySQL database using the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/sit"; 
            String user = "root";
            String password = "toor";
            Connection con = DriverManager.getConnection(url, user, password);
            String s = "select * from radission_java where phone = ?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, phone);
            ResultSet rs = ps.executeQuery();
                       
            if (rs.next()){
                name = rs.getString("Name");
                in_date = rs.getDate("in_date");
                out_date = rs.getDate("out_date");
                rooms_num = rs.getInt("rooms_num");
                delux_num = rs.getInt("delux_num");
                standard_num = rs.getInt("standard_num");
                villa_num = rs.getInt("villa_num");
                suite_num = rs.getInt("suite_num");
            }
        } catch (ClassNotFoundException | SQLException ex) {
        // Handle any exceptions that may occur while connecting to the database
        JOptionPane.showMessageDialog(null, "Internal Service Error", "Error", JOptionPane.ERROR_MESSAGE);
        System.exit(1);
        }
        
    }
    
    private void mySQLConnection_bill(double bill) throws SQLException{
        try {
            // Connect to the MySQL database using the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/sit"; 
            String user = "root";
            String password = "toor";
            Connection con = DriverManager.getConnection(url, user, password);
            String s = "UPDATE radission_java SET bill = ? WHERE phone = ?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setDouble(1, bill);
            ps.setString(2, phone);
            
            int result = ps.executeUpdate(); //returns 1 if successful
            if (result == 1)
                System.out.println("Successfully Entered Record");
            else
                System.out.println("Error in inserting Record!"); 
        } catch (ClassNotFoundException | SQLException ex) {
            // Handle any exceptions that may occur while connecting to the database
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }
    
    public void setBill(){
        bill = 0;
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String indateString = dateFormat.format(in_date);
        String outdateString = dateFormat.format(out_date);

        LocalDate inDate = LocalDate.parse(indateString, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        LocalDate outDate = LocalDate.parse(outdateString, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        long daysBetween = ChronoUnit.DAYS.between(inDate, outDate);
    
        jTextField5.setText(name);
        jTextField5.setEditable(false);
        jTextField4.setText(phone);
        jTextField4.setEditable(false);
        jTextField6.setText(indateString);
        jTextField6.setEditable(false);
        jTextField7.setText(outdateString);
        jTextField7.setEditable(false);
        jTextField8.setText(outdateString);
        jTextField8.setEditable(false);
        jTextField9.setText(String.valueOf(daysBetween) + " days"); 
        jTextField9.setEditable(false);
        
        jTextArea2.setText("");
        if (standard_num > 0) {
            jTextArea2.append(" Standard Room \n");
        }
        if (suite_num > 0) {
            jTextArea2.append(" Royal Suite \n");
        }
        if (villa_num > 0) {
            jTextArea2.append(" Villa \n");
        }
        if (delux_num > 0) {
            jTextArea2.append(" Deluxe Room \n");
        }
        
        jTextArea3.setText("");
        if (standard_num > 0) {
            jTextArea3.append(standard_num +"\n");
        }
        if (suite_num > 0) {
            jTextArea3.append(suite_num +"\n");
        }
        if (villa_num > 0) {
            jTextArea3.append(villa_num +"\n");
        }
        if (delux_num > 0) {
            jTextArea3.append(delux_num +"\n");
        }
        
        jTextArea6.setText("");
        if (standard_num > 0) {
            jTextArea6.append(String.valueOf(daysBetween) +"\n");
        }
        if (suite_num > 0) {
            jTextArea6.append(String.valueOf(daysBetween) +"\n");
        }
        if (villa_num > 0) {
            jTextArea6.append(String.valueOf(daysBetween) +"\n");
        }
        if (delux_num > 0) {
            jTextArea6.append(String.valueOf(daysBetween) +"\n");
        }
        
        jTextArea4.setText("");
        if (standard_num > 0) {
            jTextArea4.append("Rs. 6000 \n");
        }
        if (suite_num > 0) {
            jTextArea4.append("Rs. 22000 \n");
        }
        if (villa_num > 0) {
            jTextArea4.append("Rs. 17000 \n");
        }
        if (delux_num > 0) {
            jTextArea4.append("Rs. 11000 \n");
        }
        
        jTextArea1.setText("");
        if (standard_num > 0) {
            jTextArea1.append("Rs. " + 6000*standard_num*daysBetween + "\n");
            bill += 6000*standard_num*daysBetween;
        }
        if (suite_num > 0) {
            jTextArea1.append("Rs. " + 22000*suite_num*daysBetween + "\n");
            bill += 22000*suite_num*daysBetween;
        }
        if (villa_num > 0) {
            jTextArea1.append("Rs. " + 17000*villa_num*daysBetween + "\n");
            bill += 17000*villa_num*daysBetween;
        }
        if (delux_num > 0) {
            jTextArea1.append("Rs. " + 11000*delux_num*daysBetween + "\n");
            bill += 11000*delux_num*daysBetween;
        }
        jTextField10.setText("Rs. " + bill);
        
        jTextField2.setText("Rs. " + bill*0.15);
        jTextField1.setText("Rs. " + bill*0.08);
        bill = bill + bill*0.15 + bill*0.08;
        jTextField3.setText("Rs. " + bill);
        try{
            mySQLConnection_bill(bill);
        } catch (SQLException ex) {
            // Handle any exceptions that may occur while connecting to the database
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
