/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package_main;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.*;
import package_chat.*;



/**
 *
 * @author nihar, ojaswini, mudit
 */
public class WelcomeUser extends javax.swing.JFrame {
    
    /**
     * Creates new form WelcomUser
     */
    public WelcomeUser() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(648, 370));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO RADISSON WORLD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(154, 33, 342, 33);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 127, 60, 21);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(154, 119, 342, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Phone No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(52, 180, 90, 21);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(154, 179, 342, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("PROCEED TO BOOKING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(45, 258, 250, 41);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("CHAT WITH US");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(342, 258, 252, 41);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\gargm\\Desktop\\COLLEGE\\SEM 4\\java_mini_project\\java_mini_project\\bg_new.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 340);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean mySQLConnection(String username, String phone) throws SQLException {
        try {
            // Connect to the MySQL database using the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/sit";
            String user = "root";
            String password = "toor";
            Connection con = DriverManager.getConnection(url, user, password);

            // Check if the phone number already exists in the database
            String checkQuery = "SELECT Name FROM radission_java WHERE Phone = ?";
            PreparedStatement checkPs = con.prepareStatement(checkQuery);
            checkPs.setString(1, phone);
            ResultSet resultSet = checkPs.executeQuery();
            if (resultSet.next()) {
                // Phone number already exists, check if the names match
                String nameInDb = resultSet.getString("Name").toLowerCase();
                if (username.toLowerCase().equals(nameInDb)) {
                    // Phone number exists and names match, return true
                    return true;
                } else {
                    // Phone number exists but name doesn't match, return false
                    return false;
                }
            }

            // Phone number doesn't exist, continue with booking process
            String s = "INSERT INTO radission_java (Name,Phone) VALUES (?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, username);
            ps.setString(2, phone);
            int result = ps.executeUpdate(); // returns 1 if successful
            if (result == 1) {
                System.out.println("Successfully Entered Record");
                return true;
            } else {
                System.out.println("Error in inserting Record!");
                return false;
            }
        } catch (ClassNotFoundException | SQLException ex) {
            // Handle any exceptions that may occur while connecting to the database
            JOptionPane.showMessageDialog(null, "Internal Service Error", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
            return false; // unreachable
        }
    }  


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = jTextField1.getText();
        String number = jTextField2.getText();
        
        try {
            boolean success = mySQLConnection(name, number);
            if (!success) {
                String message = "A user with this phone number already exists with a different name. Please try again.";
                int choice = JOptionPane.showOptionDialog(new JFrame(), message, "Dialog", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE, null, new String[]{"Retry", "Cancel"}, "Retry");
                if (choice == JOptionPane.OK_OPTION) {
                    // User clicked "Retry", clear the input fields and return
                    jTextField1.setText("");
                    jTextField2.setText("");
                    return;
                } else {
                    // User clicked "Cancel", exit the application
                    System.exit(1);
                }
            }
        } catch (SQLException ex) {
            // Handle any exceptions that may occur while connecting to the database
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }

        
        for (int i = 0; i < number.length(); i++) {
            if (number.charAt(i) < '0' || number.charAt(i) > '9') {
                String message = "Number should only contain digits!";
                JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (number.length()!=10){
            JOptionPane.showMessageDialog(new JFrame(), "Number should be of 10 Digits", "Dialog",
        JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        else if(number.charAt(0) == '0'){
            String message = "Number should not start with 0!";
                JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
                return;
        }

        if (!name.equals("") && !number.equals("")) {
            dispose();
            BookingPage obj = new BookingPage(number);
            obj.setVisible(true);
        } else {
            String message = "Please enter both, name and phone number!";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        ChatApp c1;
        c1 = new ChatApp();
        c1.start();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public String giveName() {
        String name = jTextField1.getText();
        return name;
    }
    
    public String givePhone() {
        String phone = jTextField2.getText();
        return phone;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeUser().setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
